services:
  whoami:
    labels:
      - traefik.enable=true
      - traefik.http.routers.whoami.rule=Host(`whoami.gryta.eu`)
      - traefik.http.routers.whoami.entrypoints=websecure
      - traefik.http.routers.whoami.tls.certresolver=le
      - traefik.http.routers.whoami.middlewares=authentik-forward-auth@docker
      - traefik.http.middlewares.authentik-forward-auth.forwardauth.address=http://authentik-server:9000/outpost.goauthentik.io/auth/traefik
      - traefik.http.middlewares.authentik-forward-auth.forwardauth.trustforwardheader=true
      - traefik.http.middlewares.authentik-forward-auth.forwardauth.authresponseheaders=X-Authentik-Email,X-Authentik-Username,X-Authentik-Groups
    image: traefik/whoami:latest
    container_name: whoami
    restart: unless-stopped
    networks:
      homelab-network:
        ipv4_address: 172.20.0.20
networks:
  homelab-network:
    external: true
