# .env:
# LLDAP_JWT_SECRET=
# LLDAP_KEY_SEED=
# LLDAP_ADMIN_PASSWORD=


services:
  lldap:
    image: lldap/lldap:stable
    container_name: lldap
    restart: unless-stopped
    networks:
      homelab-network:
        ipv4_address: 172.20.0.10
    ports:
      - "17170:17170"
    volumes:
      - "lldap_data:/data"
    environment:
      LLDAP_LDAP_BASE_DN: "dc=gryta,dc=eu"
      LLDAP_JWT_SECRET: ${LLDAP_JWT_SECRET}
      LLDAP_KEY_SEED: ${LLDAP_KEY_SEED}
      LLDAP_LDAP_USER_PASS: ${LLDAP_ADMIN_PASSWORD}

      # Optional: enable password reset via SMTP
      # LLDAP_SMTP_OPTIONS__ENABLE_PASSWORD_RESET: "true"
      # LLDAP_SMTP_OPTIONS__SERVER: "smtp.example.com"
      # LLDAP_SMTP_OPTIONS__PORT: "587"
      # LLDAP_SMTP_OPTIONS__SMTP_ENCRYPTION: "STARTTLS"
      # LLDAP_SMTP_OPTIONS__USER: "no-reply@example.com"
      # LLDAP_SMTP_OPTIONS__PASSWORD: "your-smtp-password"
      # LLDAP_SMTP_OPTIONS__FROM: "no-reply <no-reply@example.com>"
      # LLDAP_SMTP_OPTIONS__TO: "admin <admin@example.com>"

volumes:
  lldap_data:
    driver_opts:
      o: bind
      type: none
      device: /mnt/quick/apps/volumes/lldap/data
      
networks:
  homelab-network:
    external: true