# .env:
# LLDAP_JWT_SECRET=
# LLDAP_KEY_SEED=
# LLDAP_ADMIN_PASSWORD=

services:
  lldap:
    labels:
      - traefik.enable=true
      - traefik.http.routers.lldap.rule=Host(`lldap.gryta.eu`)
      - traefik.http.routers.lldap.entrypoints=websecure
      - traefik.http.routers.lldap.tls.certresolver=le
      - traefik.http.routers.lldap.middlewares=authentik-forward-auth@docker
      - traefik.http.services.authentik.loadbalancer.server.port=17170
      - traefik.http.middlewares.authentik-forward-auth.forwardauth.address=http://authentik-server:9000/outpost.goauthentik.io/auth/traefik
      - traefik.http.middlewares.authentik-forward-auth.forwardauth.trustforwardheader=true
      - traefik.http.middlewares.authentik-forward-auth.forwardauth.authresponseheaders=X-Authentik-Email,X-Authentik-Username,X-Authentik-Groups
    image: lldap/lldap:stable
    container_name: lldap
    restart: unless-stopped
    networks:
      homelab-network:
        ipv4_address: 172.20.0.10
    volumes:
      - lldap_data:/data
    environment:
      LLDAP_LDAP_BASE_DN: dc=gryta,dc=eu
      LLDAP_JWT_SECRET: ${LLDAP_JWT_SECRET}
      LLDAP_KEY_SEED: ${LLDAP_KEY_SEED}
      LLDAP_LDAP_USER_PASS: ${LLDAP_ADMIN_PASSWORD}
      # Optional: enable password reset via SMTP
      # LLDAP_SMTP_OPTIONS__ENABLE_PASSWORD_RESET: "true"
      # LLDAP_SMTP_OPTIONS__SERVER: "smtp.example.com"
      # LLDAP_SMTP_OPTIONS__PORT: "587"
      # LLDAP_SMTP_OPTIONS__SMTP_ENCRYPTION: "STARTTLS"
      # LLDAP_SMTP_OPTIONS__USER: "no-reply@example.com"
      # LLDAP_SMTP_OPTIONS__PASSWORD: "your-smtp-password"
      # LLDAP_SMTP_OPTIONS__FROM: "no-reply <no-reply@example.com>"
      # LLDAP_SMTP_OPTIONS__TO: "admin <admin@example.com>"
volumes:
  lldap_data:
    driver_opts:
      o: bind
      type: none
      device: /mnt/quick/apps/volumes/lldap/data
networks:
  homelab-network:
    external: true