# Needs `touch /home/rgryta/test/filebrowser.db` before launch
# docker-compose.yml
version: '3'
name: filebrowser
services:
    filebrowser_init:
        image: alpine
        command: /bin/sh -c "touch /databases/database.db && chmod 777 /databases/database.db"
        volumes:
            - databases_volume:/databases
    filebrowser:
        image: filebrowser/filebrowser:latest
        depends_on:
            filebrowser_init:
                condition: service_completed_successfully
        volumes:
            - files_volume:/files
            - databases_volume:/databases
        user: 1000:1000
        ports:
            - 2000:2000
        configs:
            - .filebrowser.json
        command:
            - "--config=/.filebrowser.json"
configs:
    .filebrowser.json:
        content: '{"port": 2000,"baseURL": "","address": "","log": "stdout","database": "/databases/database.db","root": "/files", "username": "admin", "password": "$2b$10$CB1z02iuRS6ofTPBABTqCuDaLY8aWQVJA3Pw/BAlcTGA0SlqbPbae"}'

volumes:
    # Volume pointing to files directory where files are stored
    files_volume:
        driver: local
        driver_opts:
            type: none
            device: /e/Github
            o: bind
    databases_volume:
    