version: '3.8'
name: jellyfin

services:
  jellyfin:
    image: mattangus/jellyfin-jetson
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Warsaw
      - NVIDIA_DRIVER_CAPABILITIES=all
      - NVIDIA_VISIBLE_DEVICES=all
    # Non linuserver image
      - JELLYFIN_DATA_DIR=/config/data
      - JELLYFIN_CONFIG_DIR=/config
      - JELLYFIN_LOG_DIR=/config/log
      - JELLYFIN_CACHE_DIR=/config/cache
    networks:
      rev-proxy-net:
        ipv4_address: 172.20.0.102
    restart: always

    volumes:
      - jellyfin_config:/config
      - media:/media

networks:
  rev-proxy-net:
    external:
      name: homelab-network
volumes:
  media:
    driver: local
    driver_opts:
      type: cifs
      device: //192.168.1.1/Media
      o: username=<smb_user>,password=<smb_pass>
  jellyfin_config:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: <path>/volumes/jellyfin
