version: '3.8'
name: mail

services:
  mailserver:
    image: ghcr.io/docker-mailserver/docker-mailserver:latest
    container_name: mailserver
    hostname: <hostname>
    volumes:
      - dms_data:/var/mail/
      - dms_state:/var/mail-state/
      - dms_config:/tmp/docker-mailserver/
      - dms_certs:/etc/letsencrypt
    environment:
      - SSL_TYPE=letsencrypt
    ports:
      - "25:25"
      - "143:143"
      - "465:465"
    restart: always
    stop_grace_period: 1m
    healthcheck:
      test: "ss --listening --tcp | grep -P 'LISTEN.+:smtp' || exit 1"
      timeout: 3s
      retries: 0
      
volumes:
  dms_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: <path>/volumes/mail/data
  dms_state:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: <path>/volumes/mail/state
  dms_config:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: <path>/volumes/mail/config
  dms_certs:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: <path>/volumes/certbot/certs