version: '3.8'
name: mail

services:
  mailserver:
    image: ghcr.io/docker-mailserver/docker-mailserver:latest
    container_name: mailserver
    hostname: <hostname>
    volumes:
      - dms_data:/var/mail/
      - dms_state:/var/mail-state/
      - dms_config:/tmp/docker-mailserver/
      - dms_certs:/tmp/dms/custom-certs/:ro
    environment:
      - SSL_TYPE=manual
      # Values should match the file paths inside the container:
      - SSL_CERT_PATH=/tmp/dms/custom-certs/public.crt
      - SSL_KEY_PATH=/tmp/dms/custom-certs/private.key
    restart: always
    stop_grace_period: 1m
    healthcheck:
      test: "ss --listening --tcp | grep -P 'LISTEN.+:smtp' || exit 1"
      timeout: 3s
      retries: 0
    networks:
      rev-proxy-net:
        ipv4_address: 172.20.0.103
      
networks:
  rev-proxy-net:
    external:
      name: homelab-network
volumes:
  dms_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: <path>/volumes/mail/data
  dms_state:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: <path>/volumes/mail/state
  dms_config:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: <path>/volumes/mail/config
  dms_certs:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: <path>/volumes/mail/cert