version: '3.8'
name: myvpn

services:
  myvpn:
    image: lscr.io/linuxserver/wireguard:latest
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - SERVERURL=auto
      - SERVERPORT=51820
      - PEERS=1
      - PEERDNS=172.20.0.254
      - ALLOWEDIPS=0.0.0.0/0
      - PERSISTENTKEEPALIVE_PEERS=all
      - LOG_CONFS=true
    network_mode: container:vpn
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped