version: '3.8'
name: nginx-revproxy
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    networks:
      proxy-network:
        ipv4_address: 172.20.0.100
    ports:
      - '80:80'
      - '443:443'
      - '81:81'
    volumes:
      - nginx_data:/data
      - nginx_letsencrypt:/etc/letsencrypt

volumes:
  nginx_data:
  nginx_letsencrypt:
  
networks:
  proxy-network:
    name: homelab-network
    driver: bridge
    driver_opts:
      parent: eth0
    ipam:
      config:
        - subnet: 172.20.0.0/24
          gateway: 172.20.0.1