version: '3.8'
name: nordvpn

services:
  nordvpn:
    # build:
    #   context: .
    #   dockerfile: ./nordvpn.Dockerfile
    image: qmcgaw/gluetun
    container_name: vpn
    cap_add:
      - NET_ADMIN
    environment:
      - VPN_SERVICE_PROVIDER=nordvpn
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=<nord_pk>
      - SERVER_COUNTRIES=Netherlands
    restart: unless-stopped
    dns:
      - 172.20.0.254
    networks:
      proxy-network:
        ipv4_address: 172.20.0.103
    ports:
      - 51820:51820/udp
        
        
networks:
  proxy-network:
    name: homelab-network
    driver: bridge
    driver_opts:
      parent: eth0
    ipam:
      config:
        - subnet: 172.20.0.0/24
          gateway: 172.20.0.1