version: '3'
name: pihole-unbound

services:
  pihole:
    container_name: pi-hole
    image: pihole/pihole:latest
    restart: unless-stopped
    hostname: pi-hole
    domainname: gryta.eu
    depends_on:
      - unbound
    networks:
      rev-proxy-net:
        ipv4_address: 172.20.0.254
    volumes: # Persistent settings
      - pi_pihole:/etc/pihole
      - pi_dnsmasq:/etc/dnsmasq.d
    ports:
      - 53:53/tcp
      - 53:53/udp
    environment:
      ServerIP: 172.20.0.254
      VIRTUAL_HOST: pi-hole.gryta.eu
      WEBPASSWORD: "123456"
      TZ: "Europe/Warsaw"
      PIHOLE_DNS_: 172.20.0.253#5335
      DNSSEC: true

  unbound:
    container_name: unbound
    image: madnuttah/unbound:latest
    restart: unless-stopped
    hostname: unbound
    domainname: gryta.eu
    ports:
      - 5335:5335/tcp
      - 5335:5335/udp
    networks:
      rev-proxy-net:
        ipv4_address: 172.20.0.253
    environment:
      TZ: "Europe/Warsaw"
      ServerIP: 172.20.0.253
      VIRTUAL_HOST: unbound.gryta.eu
    healthcheck:
      test: /usr/local/unbound/sbin/healthcheck.sh
      interval: 60s
      retries: 5
      start_period: 15s
      timeout: 30s

volumes:
  pi_pihole:
  pi_dnsmasq:
  
networks:
  rev-proxy-net:
    external:
      name: homelab-network