version: '3.8'
name: pihole-unbound

services:
  pihole:
    container_name: pi-hole
    image: pihole/pihole:latest
    restart: unless-stopped
    depends_on:
      - unbound
    networks:
      rev-proxy-net:
        ipv4_address: 172.20.0.254
    volumes: # Persistent settings
      - pi_pihole:/etc/pihole
      - pi_dnsmasq:/etc/dnsmasq.d
    environment:
      WEBPASSWORD: "<password>"
      TZ: "Europe/Warsaw"
      PIHOLE_DNS_: 172.20.0.253#5335
      DNSSEC: true

  unbound:
    container_name: unbound
    image: madnuttah/unbound:latest
    restart: unless-stopped
    networks:
      rev-proxy-net:
        ipv4_address: 172.20.0.253
    environment:
      TZ: "Europe/Warsaw"
    healthcheck:
      test: /usr/local/unbound/sbin/healthcheck.sh
      interval: 60s
      retries: 5
      start_period: 15s
      timeout: 30s

volumes:
  pi_pihole:
    driver_opts:
      o: bind
      type: none
      device: <path>/volumes/pihole/pihole
  pi_dnsmasq:
    driver_opts:
      o: bind
      type: none
      device: <path>/volumes/pihole/dnsmasq

networks:
  rev-proxy-net:
    external:
      name: homelab-network