name: roundcube

services:
  roundcube:
    container_name: roundcubemail
    image: roundcube/roundcubemail:latest
    restart: unless-stopped
    networks:
      rev-proxy-net:
        ipv4_address: 172.20.0.104
    volumes:
      - roundcube_www:/var/www/html
      - roundcube_sqlite:/var/roundcube/db
    environment:
      ROUNDCUBEMAIL_DB_TYPE: "sqlite"
      ROUNDCUBEMAIL_SKIN: "elastic"
      ROUNDCUBEMAIL_DEFAULT_HOST: "tls://mail.gryta.eu"
      ROUNDCUBEMAIL_SMTP_SERVER: "ssl://mail.gryta.eu"
      ROUNDCUBEMAIL_SMTP_PORT: "465"

volumes:
  roundcube_www:
    driver_opts:
      o: bind
      type: none
      device: <path>/volumes/roundcube/www
  roundcube_sqlite:
    driver_opts:
      o: bind
      type: none
      device: <path>/volumes/roundcube/sqlite

networks:
  rev-proxy-net:
    external:
      name: homelab-network