services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: 1000:1000
    volumes:
      - jf_config:/config
      - jf_cache:/cache
      - jf_media:/media
    restart: 'unless-stopped'
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
    networks:
      homelab-network:
        ipv4_address: 172.20.0.103
    ports:
     - 8888:80
    environment:
      - JELLYFIN_PublishedServerUrl=https://jellyfin.gryta.eu
volumes:
  jf_media:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /mnt/archive/media
  jf_config:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /mnt/quick/apps/volumes/jellyfin/config
  jf_cache:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /mnt/quick/apps/volumes/jellyfin/cache
networks:
  homelab-network:
    external: true
