services:
  whatsupdocker:
    image: getwud/wud
    container_name: wud
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8888:3000
    networks:
      homelab-network:
        ipv4_address: 172.20.0.21
networks:
  homelab-network:
    external: true
