services:
  whatsupdocker:
    labels:
      - traefik.enable=true
      - traefik.http.routers.wud.rule=Host(`wud.gryta.eu`)
      - traefik.http.routers.wud.entrypoints=websecure
      - traefik.http.routers.wud.tls.certresolver=le
      - traefik.http.services.wud.loadbalancer.server.port=3000
      - traefik.http.routers.wud.middlewares=authentik-forward-auth@docker
      - traefik.http.middlewares.authentik-forward-auth.forwardauth.address=http://authentik-server:9000/outpost.goauthentik.io/auth/traefik
      - traefik.http.middlewares.authentik-forward-auth.forwardauth.trustforwardheader=true
      - traefik.http.middlewares.authentik-forward-auth.forwardauth.authresponseheaders=X-Authentik-Email,X-Authentik-Username,X-Authentik-Groups
    image: getwud/wud
    container_name: wud
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WUD_WATCHER_LOCAL_CRON=0 5 * * *
      - TZ=UTC
    networks:
      homelab-network:
        ipv4_address: 172.20.0.21
networks:
  homelab-network:
    external: true
